// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace simulator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240915180536_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TickerData", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Strength")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TickerInfoTicker")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Ticker", "Datetime");

                    b.HasIndex("TickerInfoTicker");

                    b.ToTable("PriceData");
                });

            modelBuilder.Entity("TickerInfo", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Industry")
                        .HasColumnType("longtext");

                    b.Property<decimal>("MarketCap")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sector")
                        .HasColumnType("longtext");

                    b.HasKey("Ticker");

                    b.ToTable("Tickers");
                });

            modelBuilder.Entity("TickerData", b =>
                {
                    b.HasOne("TickerInfo", "TickerInfo")
                        .WithMany("PriceData")
                        .HasForeignKey("TickerInfoTicker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TickerInfo");
                });

            modelBuilder.Entity("TickerInfo", b =>
                {
                    b.Navigation("PriceData");
                });
#pragma warning restore 612, 618
        }
    }
}
