version: "3.7"

services:
  app:
    image: investing:${VERSION}
    ports:
    - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
    - investing-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"

volumes:
  investing-mysql-data: