// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace investing.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240906192816_AddValuationInput")]
    partial class AddValuationInput
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DDMValuationInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseEPS")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("DividendWitholdingTax")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("EpsGrowth")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("GraduallyAdjust")
                        .HasColumnType("bit");

                    b.Property<int>("GrowthYears")
                        .HasColumnType("int");

                    b.Property<decimal>("PayoutRatio")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("ReturnRate")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("StableEPSGrowth")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("StablePayoutRatio")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("StableReturnRate")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int?>("ValuationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ValuationId")
                        .IsUnique()
                        .HasFilter("[ValuationId] IS NOT NULL");

                    b.ToTable("DDMValuationInputs");
                });

            modelBuilder.Entity("Valuation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("IntrinsicValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TerminalValuePV")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.ToTable("Valuations");
                });

            modelBuilder.Entity("ValuationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Characteristic")
                        .HasColumnType("int");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<int>("ValuationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("ValuationId");

                    b.ToTable("ValuationData");
                });

            modelBuilder.Entity("DDMValuationInput", b =>
                {
                    b.HasOne("Valuation", "Valuation")
                        .WithOne("ValuationInput")
                        .HasForeignKey("DDMValuationInput", "ValuationId");

                    b.Navigation("Valuation");
                });

            modelBuilder.Entity("ValuationData", b =>
                {
                    b.HasOne("Valuation", "Valuation")
                        .WithMany("Data")
                        .HasForeignKey("ValuationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Valuation");
                });

            modelBuilder.Entity("Valuation", b =>
                {
                    b.Navigation("Data");

                    b.Navigation("ValuationInput")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
